name: caffeing
description: "Caffeing"
publish_to: "none"
authors:
  - "Kyle Chang"
version: 1.0.0

environment:
  sdk: ">=3.7.2 <3.9.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_launcher_icons: 0.14.3
  fluttertoast: 8.2.12
  provider: 6.1.5
  get: 4.1.4
  http: 1.4.0
  font_awesome_flutter: 10.7.0
  flutter_spinkit: 5.2.0
  shared_preferences: 2.2.2
  flutter_secure_storage: 9.2.4
  adaptive_theme: ^3.5.0
  google_maps_flutter: 2.12.2
  firebase_core: 3.13.1
  firebase_auth: 5.5.4
  google_sign_in: 6.3.0
  flutter_svg: 2.1.0
  intl_utils: 2.8.10
  persistent_bottom_nav_bar_v2: 6.0.1
  url_launcher: 6.3.1
  share_plus: 11.0.0
  feedback_github: 1.2.1
  cloud_functions: 5.5.1
  firebase_storage: 12.4.6
  uuid: 4.5.1
  google_maps_cluster_manager_2: 3.2.0
  geolocator: 14.0.1
  app_links: 6.4.0
  flutter_dotenv: 5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: 'MaterialIcons'

  assets:
    - assets/image/
    - assets/map_style_light.json
    - assets/map_style_dark.json
    - assets/google_signin/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  arb_file_prefix: app_
  template_arbs:
    - lib/l10n/intl_en.arb
  output_dir: lib/l10n/generated
  output_class: AppLocalizations

    
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
