name: Android Build (apps/mobile)

on:
  push:
    branches:
      - main 
    paths:
      - 'apps/mobile/**' 
      - '.github/workflows/android_build.yml' 

  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest # Use an Ubuntu runner for building Android

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable 

      - name: Navigate to project directory
        run: cd apps/mobile

      - name: Get dependencies
        run: |
          cd apps/mobile 
          flutter pub get

      - name: Build Production APK
        run: |
          cd apps/mobile 
          flutter build apk --release \
            --dart-define=APP_API_ENDPOINT=${{ secrets.APP_PROD_API_ENDPOINT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-apk
          path: apps/mobile/build/app/outputs/apk/release/app-release.apk 