name: Deploy .NET WebAPI to GCP Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-central1
  SERVICE_NAME: caffeing-webapi
  SOLUTION_PATH: apps/backend/Caffeing/Caffeing.sln
  WEBAPI_PROJECT_PATH: ${{ github.workspace }}/apps/backend/Caffeing/Caffeing.WebAPI.csproj
  PUBLISH_DIR: ./publish_output

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.409'

    - name: Check .NET SDK
      run: dotnet --list-sdks


    - name: Restore NuGet packages
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

    - name: Publish WebAPI project
      run: dotnet publish ${{ env.WEBAPI_PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_DIR }} --no-build --self-contained true --runtime linux-x64 /p:UseAppHost=true

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/671405420443/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.GCP_REGION }}
        source: ${{ env.PUBLISH_DIR }}
        env_vars: |
          ASPNETCORE_ENVIRONMENT=Production
          Logging__LogLevel__Default=Information
          Logging__LogLevel__Microsoft.AspNetCore=Warning
          Cors__AllowedOrigins__0=${{ secrets.BACKEND_CORS_ORIGIN_0 }}
          Cors__AllowedMethods__0=GET
          Cors__AllowedMethods__1=POST
          Cors__AllowedMethods__2=PUT
          Cors__AllowedMethods__3=DELETE
          Cors__AllowedHeaders__0=Content-Type
          Cors__AllowedHeaders__1=Authorization
          Serilog__MinimumLevel__Default=Information
          Serilog__MinimumLevel__Override__Microsoft=Warning
          Serilog__MinimumLevel__Override__System=Warning
          Jwt__Key=${{ secrets.JWT_KEY }}
          Jwt__Issuer=com.caffeing
          Jwt__Audience=com.caffeing.app
          Jwt__ExpiresInMinutes=60
          Database__Provider=PostgreSql
          Database__Connection__DataSource=${{ secrets.DB_DATA_SOURCE }}
          Database__Connection__InitialCatalog=${{ secrets.DB_INITIAL_CATALOG }}
          Database__Connection__UserId=${{ secrets.DB_USER_ID }}
          Database__Connection__Password=${{ secrets.DB_PASSWORD }}
          Database__Connection__Pooling=true
          Database__Connection__MaxPoolSize=100
          Database__Connection__ConnectTimeout=30
          Turnstile__SecretKey=${{ secrets.TURNSTILE_SECRET_KEY }}
          Keystone__Endpoint=${{ secrets.KEYSTONE_ENDPOINT_URL }}

    - name: Cloud Run service URL
      run: |
        echo "Cloud Run service URL: https://${{ env.GCP_REGION }}-run.googleapis.com/v1/projects/${{ env.GCP_PROJECT_ID }}/locations/${{ env.GCP_REGION }}/services/${{ env.SERVICE_NAME }}"
